### ISSUE TITLE
Publish wheels to PyPI

### ISSUE THREAD

**Issue by PeterJCLaw** [lamby/django-auto-one-to-one#9]
Would it be possible to publish Python wheels to PyPI in addition to the pure source package?

Usually doing this requires very little effort when publishing the packages (especially if the publishing steps are handled in CI) and results in faster builds (and better cache usage) for dependent projects as it means they don't need to run setup.py as part of the install.

The change needed is usually along the lines of adding the following in a `setup.cfg` file:
```
[bdist_wheel]
universal = True
```
and then including `bdist_wheel` as part of the build command before publishing.

**Comment by lamby** [comment]
Released to PyPI in `3.3.4`. 👍
